### ISSUE TITLE
Order.StockPointCode

### ISSUE THREAD

**Issue by brujah** [zenta-ab/fortnox.NET#36]
This one seems to be missing, perhaps something you can add?

**Comment by brokenprogrammer** [comment]
We have not yet looked into the Warehouse module provided by Fortnox.
However if there are just missing fields like the StockPointCode I don't see a problem with adding it to the library.

I will look into it right now!

**Comment by brokenprogrammer** [comment]
I have published version 3.0.0-alpha2 to both 
Nuget: https://www.nuget.org/packages/Fortnox.NET/3.0.0-alpha2
Github packages: https://github.com/orgs/zenta-ab/packages?repo_name=fortnox.NET

Note that there might be some breaking changes in that package compared to the latest non-alpha version. Nothing super big though.

**Comment by GGAlanSmithee** [comment]
Looks like this is done, closing per @brokenprogrammer's comment

**Comment by GGAlanSmithee** [comment]
re-opening, since this issue isn't technically done until in master, my bad.
