### ISSUE TITLE
OrderService.UpdateOrderAsync

### ISSUE THREAD

**Issue by brujah** [zenta-ab/fortnox.NET#37]
I have an order with 2 articles, they both have less delivered quantities then ordered quantities but when I call the function above it produces a very weird result.

Article 1
Ordered 10, delivered 4
Article 2
Ordered 20, delivered 5

When I check intellisense just before calling await OrderService.UpdateOrderAsync(request, fortnoxOrder); I can see that it is correct but after running that line and going to Fortnox I see this:

Article 1
Delivered 0
Article 2
Delivered 5

**Comment by brujah** [comment]
I think I actually found the issue here, code is working but the client didnt have enough stock of the articles. Going to verify shortly but most likely the issue can be closed

**Comment by brokenprogrammer** [comment]
Alright please verify. If not I will have to investigate.

Please let me know!

**Comment by brujah** [comment]
> Alright please verify. If not I will have to investigate.
> 
> Please let me know!

Yes the error was with not enough stock, code works just fine so feel free to close this one (sorry about that)

**Comment by brokenprogrammer** [comment]
> > Alright please verify. If not I will have to investigate.
> > Please let me know!
> 
> Yes the error was with not enough stock, code works just fine so feel free to close this one (sorry about that)

Great that you found a solution! Thanks for letting me know.

Best of luck!
